version: '3.8'

services:
  parental-unifi:
    build: .
    image: parental-unifi-quick-set:latest
    container_name: parental-unifi-quick-set
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    # Uncomment and modify if you want to use environment variables for configuration
    # environment:
    #   - UNIFI_URL=https://192.168.1.1:8443
    #   - UNIFI_SITE=default 